spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/a107_mysql?serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
  redis:
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
        min-idle: 2
    host: localhost
    port: 6379
  data:
    mongodb:
      host: localhost
      port: 27017
      database: a107_mongodb
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
