NAVER_CLIENT_SECRET: "3uChno1v8b"
KAKAO_CLIENT_SECRET: "DGuf0uZuIjHSWb144JPJNsPBfxsSKJVD"

spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/a107_mysql?serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: true

  redis:
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
        min-idle: 2
    host: localhost
    port: 6379

  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: a107_mongodb
      username: ssafy
      password: ssafy

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  header: Authorization
  secret: rendezboosecretkeyneedsverylongsecretkeyforsafety
  access-token-validity-milliseconds: 1800000
  refresh-token-validity-milliseconds: 604800000

openvidu:
  #  url: http://i8a107.p.ssafy.io:4443/
  url: https://52.78.60.53:4443/
  secret: thisisrendezbooopenviduserversecretkey
#openvidu:
#  url: http://localhost:4443/
#  secret: MY_SECRET

logging:
  level:
    root: info
    com.ssafy: debug

cloud:
  aws:
    s3:
      bucket: rendezboo-s3
    region:
      static: ap-northeast-2
    stack:
      auto: false
    cloudfront: http://d156wamfkmlo3m.cloudfront.net/images/

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/a107_mysql?serverTimezone=Asia/Seoul
    username: root
    password: ssafy
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: true

  redis:
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
        min-idle: 2
    host: redis
    port: 6379

  data:
    mongodb:
      host: mongodb
      port: 27017
      authentication-database: admin
      database: a107_mongodb
      username: ssafy
      password: ssafy

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  header: Authorization
  secret: rendez-boo-secret-key-needs-very-long-secret-key-for-safety
  access-token-validity-milliseconds: 1800000
  refresh-token-validity-milliseconds: 604800000

#https로 요청 보내야함(http로 요청보낼시 https로 리다이렉트하고 301응답함)
openvidu:
  url: https://52.78.60.53:4443/
  secret: thisisrendezbooopenviduserversecretkey

cloud:
  aws:
    s3:
      bucket: rendezboo-s3
    region:
      static: ap-northeast-2
    stack:
      auto: false
    cloudfront: http://d156wamfkmlo3m.cloudfront.net/images/

logging:
  level:
    root: info
    com.ssafy: debug
