version: "3.7"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - a107_network

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ssafy
      MONGO_INITDB_ROOT_PASSWORD: ssafy
      MONGO_INITDB_DATABASE: a107_mongodb
    volumes:
      - ./mongodb:/data/db
    networks:
      - a107_network

  mysql:
    image: mysql:8.0.31
    volumes:
      - a107-mysql-data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ssafy
      MYSQL_DB: a107_mysql
      MYSQL_USER: ssafy
      MYSQL_PASSWORD: ssafy
    networks:
      - a107_network

  springboot:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
      - mongodb
    networks:
      - a107_network
    environment:
      SERVER_MODE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/a107_mysql?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ssafy
      AWS_ACCESS_KEY: "${AWS_ACCESS_KEY}"
      AWS_SECRET_KEY: "${AWS_SECRET_KEY}"

volumes:
  a107-mysql-data:

networks:
  a107_network: