version: "3.7"

services:
  mysql:
    image: mysql:8.0.31
    volumes:
      - a107-mysql-data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ssafy
      MYSQL_DB: a107_mysql
      MYSQL_USER: ssafy
      MYSQL_PASSWORD: ssafy
    networks:
      - a107_network

  springboot:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - a107_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/a107_mysql?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ssafy

volumes:
  a107-mysql-data:

networks:
  a107_network: